#!/bin/bash

#$ -S /bin/bash
#$ -pe smp 16
#$ -q JM,UI
#$ -cwd
#$ -j y
#$ -ckpt user
#$ -N ancient_dna_imputation_phasing_v54
#$ -m eas
#$ -M lucas-casten@uiowa.edu

##  qsub /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/code/merge_and_qc_imputed_ancient_genomes_v54.job

##
flist="/Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/filelist.txt"
rm $flist
for i in {1..22}
do
    cat "\n\n\n\n\n"
    echo "========================================="
    echo $i 
    echo "========================================="
    echo "/Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/chr${i}.with_snp_id" >> $flist 
    /Dedicated/jmichaelson-wdata/lcasten/tools/plink --bfile /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/chr${i} --exclude /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/drop_var.snplist --make-bed --out /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/chr${i}.with_snp_id
done
cat $flist

##
# head /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/chr14.bim
echo "." > /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/drop_var.snplist

##
OUTF="/Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/autosomes_qc"
/Dedicated/jmichaelson-wdata/lcasten/tools/plink --merge-list $flist --exclude /Dedicated/jmichaelson-wdata/lcasten/tools/ref_data/allen_ancient_dna_resource/v54.1.p1_1240K_public/plink/imputed/drop_var.snplist --maf 0.001 --geno 0.02 --mind 0.02 --snps-only just-acgt --make-bed --out $OUTF

## run pca_and_pgs_in_AADR.imputed.R script 
