#!/bin/bash
 
#$ -q JM,UI,CCOM
#$ -pe smp 12
#$ -cwd
#$ -N EpiSLI_subset_to_HAQERs
#$ -M lucas-casten@uiowa.edu
#$ -m eas

module load bcftools

HAQER="/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/HAQERs.bed"
HAQER1Kb="/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/data/HAQERs_plus_1Kb_flanks.bed"
HAQER5Kb="/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/data/HAQERs_plus_5Kb_flanks.bed"
HAQER10Kb="/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/data/HAQERs_plus_10Kb_flanks.bed"
VCF="/Dedicated/jmichaelson-sdata/SLI_WGS/callsets/ensemble/vcfdb_vcfanno/sli.seq.merge.norm.vep.vcfanno.vcf.gz"
VCFHAQER="/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/data/HAQER.sli.seq.merge.norm.vep.vcfanno.hg19.vcf.gz"
KEEP="/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/data/samples.fam"

## subset and index VCF
bcftools view -R $HAQER $VCF -Oz -o $VCFHAQER
bcftools view -R $HAQER1Kb $VCF -Oz -o ${VCFHAQER%.vcf.gz}.1Kb_flank.vcf.gz
bcftools view -R $HAQER5Kb $VCF -Oz -o ${VCFHAQER%.vcf.gz}.5Kb_flank.vcf.gz
bcftools view -R $HAQER10Kb $VCF -Oz -o ${VCFHAQER%.vcf.gz}.10Kb_flank.vcf.gz

tabix -p vcf $VCFHAQER

## convert to PLINK format for easy analysis
PLINK="/Dedicated/jmichaelson-wdata/lcasten/tools/plink"
#     --keep-allele-order \
$PLINK --vcf $VCFHAQER \
    --min-ac 1 \
    --keep $KEEP \
    --geno 0.02 \
    --make-bed --out ${VCFHAQER%.vcf.gz}

$PLINK --vcf ${VCFHAQER%.vcf.gz}.1Kb_flank.vcf.gz \
    --min-ac 1 \
    --keep $KEEP \
    --geno 0.02 \
    --make-bed --out ${VCFHAQER%.vcf.gz}.1Kb_flank

$PLINK --vcf ${VCFHAQER%.vcf.gz}.5Kb_flank.vcf.gz \
    --min-ac 1 \
    --keep $KEEP \
    --geno 0.02 \
    --make-bed --out ${VCFHAQER%.vcf.gz}.5Kb_flank

$PLINK --vcf ${VCFHAQER%.vcf.gz}.10Kb_flank.vcf.gz \
    --min-ac 1 \
    --keep $KEEP \
    --geno 0.02 \
    --make-bed --out ${VCFHAQER%.vcf.gz}.10Kb_flank

$PLINK --bfile ${VCFHAQER%.vcf.gz} \
    --freq --out ${VCFHAQER%.vcf.gz}.af
