#!/bin/bash

#$ -S /bin/bash
#$ -pe smp 56
#$ -q JM,CCOM,UI
#$ -cwd
#$ -j y
#$ -ckpt user

## qsub -t 1-22:1 /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/code/SPARK_WGS/pull_HAQER_genotypes.job
## qsub -t 1-3:1 /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/code/SPARK_WGS/pull_HAQER_genotypes.job 
## qsub -t 6-8:1 /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/code/SPARK_WGS/pull_HAQER_genotypes.job
## qsub -t 11-11:1 /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/code/SPARK_WGS/pull_HAQER_genotypes.job
## qsub -t 13-22:3 /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/code/SPARK_WGS/pull_HAQER_genotypes.job
conda activate saige
Rscript /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/HAQER_variant_associations/code/SPARK_WGS/pull_HAQER_genotypes.R $SGE_TASK_ID
##