#!/bin/bash
cd /Dedicated/jmichaelson-wdata/lcasten/tools/PRSice

Rscript PRSice.R --prsice PRSice_linux \
    --base /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/polygenic_neanderthal_introgression/sumstats/cogPerf.tsv \
    --target /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/1000_genomes_EUR_merge/merged.1000_genomes_EUR.SLI_WGS.qc \
    --ld-keep /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/1000_genomes_EUR_merge/LD_keep_samples.txt --binary-target T \
    --bar-levels 1 --fastscore --no-regress --thread 8 \
    --bed /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/human_chimp_divergence_DMG.matched_control_sequences.bed:random_matched_control_human_chimp_div_DMG,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/HAQERs.matched_control_sequences.bed:random_matched_control_HAQER,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/HARs.matched_control_sequences.bed:random_matched_control_HAR,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/primate_UCE.hg19.matched_control_sequences.bed:random_matched_control_consPrimates_UCE,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/LinAR_Catarrhini.matched_control_sequences.bed:random_matched_control_LinAR_Catarrhini,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/LinAR_Hominidae.matched_control_sequences.bed:random_matched_control_LinAR_Hominidae,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/LinAR_Homininae.matched_control_sequences.bed:random_matched_control_LinAR_Homininae,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/LinAR_Hominoidea.matched_control_sequences.bed:random_matched_control_LinAR_Hominoidea,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/LinAR_Human.matched_control_sequences.bed:random_matched_control_LinAR_Human,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/LinAR_Simiformes.matched_control_sequences.bed:random_matched_control_LinAR_Simiformes,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/chimp-AQERs.matched_control_sequences.bed:random_matched_control_CAQERs,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/gorilla-AQERs.matched_control_sequences.bed:random_matched_control_GAQERs,/Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/gene_sets/HAQERs_v2.hg19.matched_control_sequences.bed:random_matched_control_HAQER_v2 \
    --print-snp \
    --out /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/prs/pathway_prs/cogPerf.human_evolution_matched_control_regions