#!/bin/bash

#$ -S /bin/bash
#$ -pe smp 56
#$ -q JM,CCOM,UI
#$ -cwd
#$ -j y
#$ -ckpt user
#$ -N PRSset_SLI_WGS
#$ -m eas
#$ -M lucas-casten@uiowa.edu

## qsub /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/polygenic_neanderthal_introgression/code/prset.job

conda activate RERCONVERGE

# bash /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/polygenic_neanderthal_introgression/code/prset.sh
bash /Dedicated/jmichaelson-wdata/lcasten/sli_wgs/polygenic_neanderthal_introgression/code/prset_v2.sh